name: khat_application
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.5
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/khat2.png
  image_dark: assets/images/khat2.png
  
  android_12:
    image: assets/images/khat2.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/khat2.png
    icon_background_color_dark: "#272727"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf  


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
