// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuaEBBlg94GP3wkqgPZGNnBF439CbqdVs',
    appId: '1:140888341473:web:c98b1b28ea180e38ff30a0',
    messagingSenderId: '140888341473',
    projectId: 'khatplatform',
    authDomain: 'khatplatform.firebaseapp.com',
    storageBucket: 'khatplatform.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5QdvaWf9pE-JFVwtqV6bOBimqXCFBLdk',
    appId: '1:140888341473:android:e6fff419891e7cd5ff30a0',
    messagingSenderId: '140888341473',
    projectId: 'khatplatform',
    storageBucket: 'khatplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmXEtbh06RsVFZibHAB-tIyn-i9G4Djs',
    appId: '1:140888341473:ios:36ae162dcf6f3773ff30a0',
    messagingSenderId: '140888341473',
    projectId: 'khatplatform',
    storageBucket: 'khatplatform.appspot.com',
    iosBundleId: 'com.example.khatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMmXEtbh06RsVFZibHAB-tIyn-i9G4Djs',
    appId: '1:140888341473:ios:de6ae954a27f8782ff30a0',
    messagingSenderId: '140888341473',
    projectId: 'khatplatform',
    storageBucket: 'khatplatform.appspot.com',
    iosBundleId: 'com.example.khatApplication.RunnerTests',
  );
}
